-- ============================================================
-- AYUDERMA SUPABASE DATABASE SCHEMA MIGRATION & SEED DATA
-- Run this script in the Supabase SQL Editor to initialize tables
-- ============================================================

-- 1. Create 'diseases' table
CREATE TABLE IF NOT EXISTS diseases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disease_name TEXT NOT NULL UNIQUE,
    description TEXT,
    causes TEXT,
    symptoms TEXT,
    severity TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create 'medicines' table
CREATE TABLE IF NOT EXISTS medicines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disease_id BIGINT REFERENCES diseases(id) ON DELETE CASCADE,
    medicine_name TEXT NOT NULL,
    description TEXT,
    usage TEXT,
    precautions TEXT
);

-- 3. Create 'diets' table
CREATE TABLE IF NOT EXISTS diets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disease_id BIGINT REFERENCES diseases(id) ON DELETE CASCADE,
    recommendation_type TEXT DEFAULT 'recommended', -- 'recommended' or 'avoid'
    food TEXT NOT NULL,
    description TEXT
);

-- Enable Row Level Security (RLS) and grant read access to authenticated/anon roles
ALTER TABLE diseases ENABLE ROW LEVEL SECURITY;
ALTER TABLE medicines ENABLE ROW LEVEL SECURITY;
ALTER TABLE diets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on diseases" ON diseases FOR SELECT USING (true);
CREATE POLICY "Allow public read access on medicines" ON medicines FOR SELECT USING (true);
CREATE POLICY "Allow public read access on diets" ON diets FOR SELECT USING (true);

-- 4. Create 'skin_scans' table
CREATE TABLE IF NOT EXISTS skin_scans (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    image_path TEXT,
    image_url TEXT,
    predicted_disease TEXT,
    confidence DOUBLE PRECISION,
    skin_health_score INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS) and grant read/write access
ALTER TABLE skin_scans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on skin_scans" ON skin_scans FOR SELECT USING (true);
CREATE POLICY "Allow public insert access on skin_scans" ON skin_scans FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access on skin_scans" ON skin_scans FOR UPDATE USING (true);
CREATE POLICY "Allow public delete access on skin_scans" ON skin_scans FOR DELETE USING (true);

-- ============================================================
-- SEED INITIAL DATA FOR ALL 11 SKIN DISEASE CLASSES
-- ============================================================

INSERT INTO diseases (disease_name, description, causes, symptoms, severity)
VALUES 
('Tinea Ringworm Candidiasis', 'Fungal skin infection caused by dermatophytes or Candida, resulting in itchy ring-shaped or erythematous patches.', 'Kapha-Pitta aggravation caused by moisture retention, sweat accumulation, and dampened skin Agni.', 'Red circular scaling patches, intense itching, peripheral erythema, fungal lesion expansion.', 'Moderate'),
('Warts Molluscum OR other Viral Infections', 'Benign viral skin growths caused by human papillomavirus (HPV) or poxvirus.', 'Vata-Kapha vitiation leading to localized Mamsa Dhatu (muscle tissue) hyper-growth.', 'Small firm flesh-colored papules, umbilicated lesions, mild localized skin tightness.', 'Mild'),
('Basal Cell Carcinoma (BCC)', 'A common form of skin cancer arising in the basal cells of the epidermis.', 'Chronic ultraviolet (UV) light exposure causing severe Dhatu vitiation.', 'Pearly or waxy bump, non-healing open sore, rolled borders, translucent micro-vessels.', 'High'),
('Benign Keratosis-like Lesions (BKL)', 'Non-cancerous skin growths such as seborrheic keratoses or solar lentigines.', 'Vata accumulation in epidermal skin layers with age-related melanocyte changes.', 'Waxy, scaly plaques with light to dark brown pigmentation, stuck-on appearance.', 'Low'),
('Dermatitis', 'General skin inflammation featuring erythema, pruritus, and dry scaly patches.', 'Acute Pitta-Vata flare triggered by allergen contact, harsh chemical cosmetics, or systemic heat.', 'Erythematous skin rash, burning sensation, intense itching, localized redness.', 'Moderate'),
('Eczema', 'Chronic inflammatory skin condition causing itchy, dry, cracked skin (Vicharchika).', 'Kapha-Pitta imbalance with Rakta Dhatu impurity and compromised skin lipid barrier.', 'Dry, intensely itchy, inflamed patches, lichenified skin, loss of natural moisture.', 'Moderate to High'),
('Atopic Dermatitis', 'An allergic skin flare common in prone individuals, causing intense itching and skin scaling.', 'Tridosha vitiation with dominant Vata dryness and Pitta inflammatory response.', 'Pruritic red rash, skin flaking, dry patches on flexural folds, skin sensitivity.', 'Moderate'),
('Melanocytic Nevi (NV)', 'Common benign skin mole composed of melanocytes.', 'Benign localized accumulation of Bhrajaka Pitta and melanin pigment.', 'Uniformly pigmented tan/brown macule or papule, distinct smooth symmetrical borders.', 'Low'),
('Melanoma', 'Serious form of skin cancer that begins in melanocytes.', 'High-risk malignant melanocytic transformation due to severe DNA/UV damage.', 'Asymmetrical dark lesion, irregular notched borders, color variation, evolving size.', 'Critical'),
('Normal', 'No supported skin disease or lesion detected. Healthy skin balance.', 'Balanced Tridosha (Harmonious Vata, Pitta, and Kapha equilibrium).', 'Even skin tone, balanced sebum secretion, smooth texture, healthy complexion.', 'Healthy'),
('Psoriasis', 'Autoimmune skin condition causing rapid skin cell buildup leading to scaly patches (Ekakushta).', 'Vata-Kapha dryness coupled with Pitta inflammation and immune hyper-reactivity.', 'Silvery-white scaly plaques, erythematous base, thickened skin patches, severe dryness.', 'High'),
('Seborrheic Keratoses', 'Common non-cancerous skin growth that appears as a waxy brown or black plaque.', 'Age-related Vata-Kapha accumulation in outer epidermal layers.', 'Benign raised warty plaque, brown/black pigmented surface, distinct rounded borders.', 'Low')
ON CONFLICT (disease_name) DO NOTHING;

-- Seed sample medicines
INSERT INTO medicines (disease_id, medicine_name, description, usage, precautions)
SELECT id, 'Neem & Karanja Paste', 'Potent antimicrobial and antifungal botanical formulation.', 'Apply bi-daily over affected areas after washing with Triphala water.', 'Avoid open broken lesions; perform spot patch test first.'
FROM diseases WHERE disease_name = 'Tinea Ringworm Candidiasis';

INSERT INTO medicines (disease_id, medicine_name, description, usage, precautions)
SELECT id, 'Khadirarishta', 'Classical Ayurvedic liquid tonic for blood purification and skin health.', '15-20 ml twice daily with equal quantity of warm water after meals.', 'Consult physician during pregnancy.'
FROM diseases WHERE disease_name = 'Tinea Ringworm Candidiasis';

INSERT INTO medicines (disease_id, medicine_name, description, usage, precautions)
SELECT id, 'Shatadhauta Ghrita (100x Washed Ghee)', 'Profoundly soothing cooling balm that heals dermal inflammation.', 'Apply a thin layer to inflamed skin twice daily.', 'Ensure sterile application.'
FROM diseases WHERE disease_name = 'Dermatitis';

INSERT INTO medicines (disease_id, medicine_name, description, usage, precautions)
SELECT id, 'Wrightia Tinctoria Herbal Oil', 'Renowned traditional herbal oil for scaling psoriasis plaques.', 'Apply gently over affected plaques 30 minutes before bathing.', 'Do not forcibly pick or peel scales.'
FROM diseases WHERE disease_name = 'Psoriasis';

-- Seed sample diets
INSERT INTO diets (disease_id, recommendation_type, food, description)
SELECT id, 'recommended', 'Bitter Greens & Neem Tea', 'Cleanses blood heat and suppresses fungal moisture.'
FROM diseases WHERE disease_name = 'Tinea Ringworm Candidiasis';

INSERT INTO diets (disease_id, recommendation_type, food, description)
SELECT id, 'avoid', 'Fermented Foods & Sugars', 'Increases fungal proliferation and aggravates moisture.'
FROM diseases WHERE disease_name = 'Tinea Ringworm Candidiasis';

INSERT INTO diets (disease_id, recommendation_type, food, description)
SELECT id, 'recommended', 'Coconut Water & Cucumber', 'Cools Pitta blood heat and reduces cutaneous erythema.'
FROM diseases WHERE disease_name = 'Dermatitis';

INSERT INTO diets (disease_id, recommendation_type, food, description)
SELECT id, 'recommended', 'Ghee & Boiled Mung Beans', 'Soothes Vata dryness and calms Pitta immune inflammation.'
FROM diseases WHERE disease_name = 'Psoriasis';
